//
//  ParentViewViewController.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentViewDisplayLogic: class {
    func displayGreeting(viewModel: Parent.ShowGreeting.ViewModel)
    func dispalyTellChild(viewModel: Parent.TellChild.ViewModel)
}

extension ParentViewViewController: ParentViewDisplayLogic {
    func displayGreeting(viewModel: Parent.ShowGreeting.ViewModel) {
        label.text = viewModel.greeting
    }
    
    func dispalyTellChild(viewModel: Parent.TellChild.ViewModel) {
        router?.routeToChild(segue: nil)
    }
    
}

class ParentViewViewController: UIViewController {
    
    // MARK: - IBOutlets
    @IBOutlet weak var label: UILabel!
    @IBOutlet weak var textField: UITextField!
     
    // MARK: - Properties
    var interator: ParentViewBusinessLogic?
    var router: (NSObjectProtocol & ParentViewRoutingLogic & ParentViewDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setup() {
        ParentViewConfigurator.shared.config(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        showGreeting()
    }
    
    // MARK: - IBAction
    @IBAction func bntPressed(_ sender: UIButton) {
        tellChild()
    }
    
    private func tellChild() {
        let name = textField.text
        let request = Parent.TellChild.Request(name: name ?? "")
        interator?.tellChild(request: request)
    }
    
    private func showGreeting() {
        let request = Parent.ShowGreeting.Request()
        interator?.showGreetings(request: request)
    }
    
}
