//
//  ParentViewPresenter.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentViewPresentationLogic {
    func presentGreeting(response: Parent.ShowGreeting.Response)
    func presentTellChild(response: Parent.TellChild.Response)
}

class ParentViewPresenter: ParentViewPresentationLogic {
    weak var viewController: ParentViewDisplayLogic?
    
    // MARK: - ParentViewPresenter
    func presentGreeting(response: Parent.ShowGreeting.Response) {
        let greeting = response.name.isEmpty ? "Hello" : "\(response.name), nah, let's just shop on Amazon on my iPad."
        let viewModel = Parent.ShowGreeting.ViewModel(greeting: greeting)
        viewController?.displayGreeting(viewModel: viewModel)
    }
    
    func presentTellChild(response: Parent.TellChild.Response) {
        let viewModel = Parent.TellChild.ViewModel()
        viewController?.dispalyTellChild(viewModel: viewModel)
    }
}
