//
//  ParentViewRouter.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ParentViewRoutingLogic {
    func routeToChild(segue: UIStoryboard?)
}

protocol ParentViewDataPassing {
      var dataStore: ParentViewDataStore? { get }
}

class ParentViewRouter: NSObject, ParentViewRoutingLogic, ParentViewDataPassing {
    
    // MARK: - ParentViewRoutingLogic
    func routeToChild(segue: UIStoryboard?) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let destinationViewController = storyboard.instantiateViewController(withIdentifier: "ChildViewViewController") as? ChildViewViewController,
            var destinationDataStore = destinationViewController.router?.dataStore,
            let dataStore = dataStore,
            let viewController = viewController else { return }
        // passing data
        passDataToTheChild(source: dataStore, destination: &destinationDataStore)
        navigateToTheChild(source: viewController, destination: destinationViewController)
    }
    
    // MARK: - Passing data
    func passDataToTheChild(source: ParentViewDataStore, destination: inout ChildViewDataStore) {
        destination.name = source.name
    }
    
    func navigateToTheChild(source: ParentViewViewController, destination: ChildViewViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: - CleanSwift connection
    weak var viewController: ParentViewViewController?
    var dataStore: ParentViewDataStore?
}
