//
//  ParentViewInteractor.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentViewBusinessLogic {
    func showGreetings(request: Parent.ShowGreeting.Request)
    func tellChild(request: Parent.TellChild.Request)
}

protocol ParentViewDataStore {
    var name: String { get set }
}

class ParentViewInteractor: ParentViewBusinessLogic, ParentViewDataStore {
    
    // MARK: - Clean-swift connection
    var name: String = ""
    var presenter: ParentViewPresentationLogic?
    
    // MARK: - ParentViewBusinessLogic
    func showGreetings(request: Parent.ShowGreeting.Request) {
        let response = Parent.ShowGreeting.Response(name: name)
        presenter?.presentGreeting(response: response)
        
    }
    
    func tellChild(request: Parent.TellChild.Request) {
        name = request.name
        let response = Parent.TellChild.Response()
        presenter?.presentTellChild(response: response)
    }
}
