//
//  ChildViewInteractor.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildViewBusinessLogic {
    func showGreeting(request: Child.ShowGreetings.Request)
    func tellParent(request: Child.TellParent.Request)
}

protocol ChildViewDataStore {
    var name: String { get set }
}

class ChildViewInteractor: ChildViewBusinessLogic, ChildViewDataStore {
    
    // MARK: - ChildViewBusinessLogic
    func showGreeting(request: Child.ShowGreetings.Request) {
        let request = Child.ShowGreetings.Response(name: name)
        presenter?.presentGreeting(response: request)
    }
    
    func tellParent(request: Child.TellParent.Request) {
        name = request.name
        let response = Child.TellParent.Response()
        presenter?.presetTellParent(response: response)
    }
    
    var name: String = ""
    var presenter: ChildViewPresentationLogic?
}
