//
//  ChildViewModels.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Child {
    // MARK: Use cases
    enum ShowGreetings {
        struct Request {}
        struct Response {
            var name: String
        }
        struct ViewModel {
            var greeting: String
        }
    }
    
    enum TellParent {
        struct Request {
            var name: String
        }
        struct Response {}
        struct ViewModel {}
    }
}
