//
//  ChildViewPresenter.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildViewPresentationLogic {
    func presentGreeting(response: Child.ShowGreetings.Response)
    func presetTellParent(response: Child.TellParent.Response)
}

class ChildViewPresenter: ChildViewPresentationLogic {
    
    // MARK: - VIP Cycle connection
    weak var viewController: ChildViewDisplayLogic?
    
    // MARK: - ChildViewPresentationLogic
    func presentGreeting(response: Child.ShowGreetings.Response) {
        let greeting = response.name.isEmpty ? "Hello" : "\(response.name),do you want to go to Toys R Us before they bankrupt?"
        let viewModel = Child.ShowGreetings.ViewModel(greeting: greeting)
        viewController?.displayGreeting(viewModel: viewModel)
    }
    
    func presetTellParent(response: Child.TellParent.Response) {
        let viewModel = Child.TellParent.ViewModel()
        viewController?.displayTellParent(viewModel: viewModel)
    }
}
