//
//  ChildViewRouter.swift
//  DataPassingVIPExample
//
//  Created by Yani Buchkov on 21.11.18.
//  Copyright (c) 2018 Yani Buchkov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChildViewRoutingLogic {
    func routeToParent(segue: UIStoryboard?)
}

protocol ChildViewDataPassing {
    var dataStore: ChildViewDataStore? { get }
}

class ChildViewRouter: NSObject, ChildViewRoutingLogic, ChildViewDataPassing {
    
    // MARK: - Clean-swift connection
    weak var viewController: ChildViewViewController?
    var dataStore: ChildViewDataStore?
    
    // MARK: Routing
    func routeToParent(segue: UIStoryboard?) {
        guard let destinationViewController = viewController?.presentingViewController as? ParentViewViewController,
            var destinationDataStore = destinationViewController.router?.dataStore,
            let dataStore = dataStore,
            let viewController = viewController else { return }
        passDataToTheParent(source: dataStore, destination: &destinationDataStore)
        navigateToTheParent(source: viewController, destination: destinationViewController)
    }
    
    // MARK: - Passing data
    func passDataToTheParent(source: ChildViewDataStore, destination: inout ParentViewDataStore) {
        destination.name = source.name
    }
    
    // MARK: - Navigation
    func navigateToTheParent(source: ChildViewViewController, destination: ParentViewViewController) {
        source.dismiss(animated: true, completion: nil)
    }
}
